### ISSUE TITLE
[Regression] Everything's missing?

### ISSUE THREAD

**Issue by NightMachinery** [webinstall/webi-installer-requests#20] opened 2023-09-15 08:38 UTC
Any package that I try, I get this error:
```
$ curl -sS https://webi.sh/fd | sh
 
"fd" Not found.
 
See https://webinstall.dev/ for featured installers
or https://webinstall.dev/sitemap.xml for a list of all installers
 
Think "fd" is something we should have? Let us know:
 
  https://github.com/webinstall/webi-installer-requests/issues/new?title=Add%20fd
 
```

**Comment by coolaj86** [comment] 2023-10-12 06:06
That's very strange.

I didn't notice this myself and I don't think we had any other reports about it.

Perhaps it was just some momentary downtime during a deploy...

Thanks for the report and I wish I had seen it just as it was happening to know what the cause was, but I'll close it out since I don't think it was more than a hiccup.

**Closed as completed by coolaj86** 2023-10-12 06:06 UTC
